esphome:
  name: smartknob
  
external_components:
  - source:
      type: git
      url: https://github.com/KrX3D/waveshare-knob-audio-mic
      ref: main
    refresh: 0s
    components: [audio_mic]

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      # Enable long file names for SD card
      CONFIG_FATFS_LFN_STACK: "y"

logger:
  level: DEBUG