esphome:
  name: smartknob_stage1_speaker_only
  on_boot:
    priority: 700
    then:
      - output.turn_on: dac_route_en

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal

logger:
api:
ota:

output:
  - platform: gpio
    pin: GPIO0
    id: dac_route_en

i2s_audio:
  - id: i2s_out
    i2s_bclk_pin: GPIO39
    i2s_lrclk_pin: GPIO40

speaker:
  - platform: i2s_audio
    id: spk_out
    i2s_audio_id: i2s_out
    dac_type: external
    i2s_dout_pin: GPIO41
    channel: mono
